### ISSUE TITLE
cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin. exit

### ISSUE THREAD

**Issue by Caizhenyu** [arduino/arduino-builder#188] opened 2016-11-02 02:53 UTC
I meet a problem when i complie the code,any code.Can anyone help me?
```
cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.

exit status 1
```

```
code:

setup()
{}
loop()
{}
```
```
console:
E:\arduino\arduino-builder -dump-prefs -logger=machine -hardware E:\arduino\hardware -tools E:\arduino\tools-builder -tools E:\arduino\hardware\tools\avr -built-in-libraries E:\arduino\libraries -libraries E:\Documents\Arduino\libraries -fqbn=arduino:avr:uno -ide-version=10612 -build-path C:\Users\myName\AppData\Local\Temp\arduino_build_650628 -warnings=none -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=E:\arduino\hardware\tools\avr -verbose C:\Users\myName\Desktop\sketch_oct17a\sketch_oct17a.ino
E:\arduino\arduino-builder -compile -logger=machine -hardware E:\arduino\hardware -tools E:\arduino\tools-builder -tools E:\arduino\hardware\tools\avr -built-in-libraries E:\arduino\libraries -libraries E:\Documents\Arduino\libraries -fqbn=arduino:avr:uno -ide-version=10612 -build-path C:\Users\myName\AppData\Local\Temp\arduino_build_650628 -warnings=none -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=E:\arduino\hardware\tools\avr -verbose C:\Users\myName\Desktop\sketch_oct17a\sketch_oct17a.ino
Using board 'uno' from platform in folder: E:\arduino\hardware\arduino\avr
Using core 'arduino' from platform in folder: E:\arduino\hardware\arduino\avr
Detecting libraries used...
"E:\arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10612 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IE:\arduino\hardware\arduino\avr\cores\arduino" "-IE:\arduino\hardware\arduino\avr\variants\standard" "C:\Users\myName\AppData\Local\Temp\arduino_build_650628\sketch\sketch_oct17a.ino.cpp" -o "nul"
"E:\arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10612 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IE:\arduino\hardware\arduino\avr\cores\arduino" "-IE:\arduino\hardware\arduino\avr\variants\standard" "C:\Users\myName\AppData\Local\Temp\arduino_build_650628\sketch\sketch_oct17a.ino.cpp" -o "nul"
Generating function prototypes...
"E:\arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10612 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IE:\arduino\hardware\arduino\avr\cores\arduino" "-IE:\arduino\hardware\arduino\avr\variants\standard" "C:\Users\myName\AppData\Local\Temp\arduino_build_650628\sketch\sketch_oct17a.ino.cpp" -o "C:\Users\myName\AppData\Local\Temp\arduino_build_650628\preproc\ctags_target_for_gcc_minus_e.cpp"
"E:\arduino\tools-builder\ctags\5.8-arduino10/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\Users\myName\AppData\Local\Temp\arduino_build_650628\preproc\ctags_target_for_gcc_minus_e.cpp"
compile...
"E:\arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10612 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IE:\arduino\hardware\arduino\avr\cores\arduino" "-IE:\arduino\hardware\arduino\avr\variants\standard" "C:\Users\myName\AppData\Local\Temp\arduino_build_650628\sketch\sketch_oct17a.ino.cpp" -o "C:\Users\myName\AppData\Local\Temp\arduino_build_650628\sketch\sketch_oct17a.ino.cpp.o"
Compiling libraries...
Compiling core...
"E:\arduino\hardware\tools\avr/bin/avr-gcc" -c -g -x assembler-with-cpp -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10612 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IE:\arduino\hardware\arduino\avr\cores\arduino" "-IE:\arduino\hardware\arduino\avr\variants\standard" "E:\arduino\hardware\arduino\avr\cores\arduino\wiring_pulse.S" -o "C:\Users\myName\AppData\Local\Temp\arduino_build_650628\core\wiring_pulse.S.o"
"E:\arduino\hardware\tools\avr/bin/avr-gcc" -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10612 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IE:\arduino\hardware\arduino\avr\cores\arduino" "-IE:\arduino\hardware\arduino\avr\variants\standard" "E:\arduino\hardware\arduino\avr\cores\arduino\WInterrupts.c" -o "C:\Users\myName\AppData\Local\Temp\arduino_build_650628\core\WInterrupts.c.o"
cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.

exit status 1
```

**Comment by facchinm** [comment] 2016-11-02 12:13
Duplicate of https://github.com/arduino/arduino-builder/issues/186, continuing discussion there

**Closed by facchinm** 2016-11-02 12:13 UTC
