### ISSUE TITLE
Parallelize builds

### ISSUE THREAD

**Issue by xcvista** [arduino/arduino-builder#168] opened 2016-07-09 20:44 UTC
I seriously doubt if anyone here are still stuck with a single-core processor. My three computers have 2, 4 and 16 hyper-threading cores respectively. Since almost everyone have a multi-core (or at least hyper-threading) processor why not take advantage of it, by parallelizing the build process?

Multiple instances of GCC can be launched at the same time. So you can perform core count detection upon launch (people can upgrade their processors after installing the software) and when compiling, use as many cores as possible. Building multi-compile-unit code is an embarrassingly parallel problem.

As of presentation, the `-k` flag from GNU Make is my personal favorite.

**Comment by per1234** [comment] 2016-07-10 03:10
See https://github.com/arduino/arduino-builder/issues/17. It looks like some work has been done towards this in the [parallel branch](https://github.com/arduino/arduino-builder/tree/parallel).

**Comment by cmaglie** [comment] 2016-08-26 16:04
Duplicate of #17

**Closed by cmaglie** 2016-08-26 16:04 UTC
