### ISSUE TITLE
Incorrect prototype when using constexpr

### ISSUE THREAD

**Issue by Chris--A** [arduino/arduino-builder#170] opened 2016-07-25 21:40 UTC
Using 1.6.10 IDE compiled a few days ago.

This code requires a manual prototype, otherwise the IDE combines the `constexpr` and `int` causing an undeclared type error.

``` C++
constexpr int test();
constexpr int test() { return 5; }

void setup() {
  Serial.begin(9600);
  Serial.println(test());
}

void loop() {
}
```

**Comment by esorton** [comment] 2016-08-01 18:38
I can confirm this issue on Windows 10/Arduino IDE 1.6.9 and 1.6.10.

**Comment by matthijskooijman** [comment] 2016-08-01 20:42
I can reproduce this as well. This seems to be a problem in ctags, which gets the returntype wrong.

    test    /tmp/arduino_modified_sketch_261104/sketch_aug01a.ino   /^constexpr int test() { return 5; }$/;"        kind:function   line:2  signature:()    returntype:constexprint

@igrr, perhaps we could persuade you to have a look at this? I would presume this is as simple as letting ctags know that `constexpr` is a keyword?

**Comment by esorton** [comment] 2016-08-02 03:10
Adding `constexpr` as a keyword in arduino/arduino-ctags fixed the issue for me.  Created pull request arduino/ctags#11.

**Comment by matthijskooijman** [comment] 2016-08-02 07:38
Awesome, thanks!

**Comment by facchinm** [comment] 2016-12-19 08:29
Fixed by merging https://github.com/arduino/ctags/pull/11

**Closed by facchinm** 2016-12-19 08:29 UTC
